# Generated by Django 3.2.7 on 2021-11-15 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RestModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timein', models.DateTimeField()),
                ('timeout', models.DateTimeField()),
                ('appliance', models.CharField(max_length=50)),
                ('kwh', models.PositiveIntegerField()),
            ],
        ),
    ]
