# Generated by Django 3.2.7 on 2021-11-15 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restmodel',
            name='timein',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='restmodel',
            name='timeout',
            field=models.DateTimeField(null=True),
        ),
    ]
