# Generated by Django 3.2.7 on 2021-11-15 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20211115_2325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restmodel',
            name='timein',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='restmodel',
            name='timeout',
            field=models.TimeField(null=True),
        ),
    ]
