# Generated by Django 3.2.7 on 2021-11-18 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20211115_2347'),
    ]

    operations = [
        migrations.CreateModel(
            name='OtpModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=120, null=True)),
                ('unique', models.CharField(max_length=130)),
                ('email', models.CharField(max_length=130)),
                ('otp', models.PositiveIntegerField()),
                ('password', models.CharField(max_length=130)),
            ],
        ),
    ]
