# Generated by Django 3.2.7 on 2021-11-18 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_otpmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appliance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=12, null=True)),
                ('appliance', models.ImageField(upload_to='producting')),
                ('category', models.CharField(choices=[('Hw', 'Heavy'), ('Lt', 'Light')], max_length=10)),
                ('kwh', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Otp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique', models.CharField(max_length=130)),
                ('email', models.CharField(max_length=130)),
                ('otp', models.PositiveIntegerField()),
                ('password', models.CharField(max_length=130)),
            ],
        ),
        migrations.RenameModel(
            old_name='RestModel',
            new_name='Rest',
        ),
        migrations.DeleteModel(
            name='OtpModel',
        ),
    ]
