# Generated by Django 3.2.7 on 2021-11-20 12:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20211118_0928'),
    ]

    operations = [
        migrations.AddField(
            model_name='appliance',
            name='state',
            field=models.CharField(default='', max_length=12),
        ),
        migrations.AddField(
            model_name='appliance',
            name='unique',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='app.otp'),
        ),
    ]
