# Generated by Django 3.2.7 on 2021-11-20 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20211120_1827'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appliance',
            name='unique',
        ),
    ]
