# Generated by Django 3.2.7 on 2021-11-20 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_remove_appliance_unique'),
    ]

    operations = [
        migrations.AddField(
            model_name='appliance',
            name='unique',
            field=models.CharField(default=10, max_length=10),
        ),
    ]
