# Generated by Django 3.2.7 on 2021-11-20 15:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_appliance_unique'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique', models.CharField(max_length=130)),
                ('timein', models.CharField(max_length=50, null=True)),
                ('timeout', models.CharField(max_length=50, null=True)),
                ('appliance', models.CharField(max_length=50)),
                ('kwh', models.PositiveIntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Rest',
        ),
        migrations.RenameField(
            model_name='appliance',
            old_name='appliance',
            new_name='image',
        ),
        migrations.RemoveField(
            model_name='appliance',
            name='unique',
        ),
        migrations.CreateModel(
            name='CustomAppliance',
            fields=[
                ('appliance_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app.appliance')),
                ('unique', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.otp')),
            ],
            bases=('app.appliance',),
        ),
    ]
