# Generated by Django 3.2.7 on 2021-11-20 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20211120_2117'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appliance',
            name='state',
        ),
        migrations.AddField(
            model_name='feature',
            name='state',
            field=models.CharField(default='', max_length=12),
        ),
    ]
