# Generated by Django 3.2.7 on 2021-11-20 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_auto_20211120_2229'),
    ]

    operations = [
        migrations.AddField(
            model_name='feature',
            name='bill',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='feature',
            name='e_consumption',
            field=models.IntegerField(max_length=50, null=True),
        ),
    ]
