# Generated by Django 3.2.7 on 2021-11-20 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_auto_20211120_2236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feature',
            name='e_consumption',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
